# Generated by Django 6.0.3 on 2026-03-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_about_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="header_name_preference",
            field=models.CharField(
                choices=[("username", "Username"), ("name", "Имя")],
                default="username",
                max_length=20,
            ),
        ),
    ]
