# Generated by Django 6.0.3 on 2026-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_header_name_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="header_name_preference",
            field=models.CharField(
                choices=[("username", "Никнэйм"), ("name", "Имя")],
                default="username",
                max_length=20,
            ),
        ),
    ]
