# Generated by Django 6.0.3 on 2026-03-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moment', '0002_alter_moment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный момент'),
        ),
    ]
