# Generated by Django 6.0.3 on 2026-04-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moment", "0003_moment_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moment",
            name="title",
            field=models.CharField(
                help_text="Подарите моменту название",
                max_length=100,
                verbose_name="Название момента",
            ),
        ),
    ]
